# Generated by Django 3.2.8 on 2021-11-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_editprofileform'),
    ]

    operations = [
        migrations.AddField(
            model_name='editprofileform',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
    ]
