# Generated by Django 3.2.8 on 2021-11-16 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_quillpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
    ]
