# Generated by Django 3.2.8 on 2021-11-16 04:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_quillpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofileform',
            name='bio',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
