# Generated by Django 3.2.8 on 2021-11-16 04:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_editprofileform_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofileform',
            name='bio',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
