# Generated by Django 3.2.8 on 2021-11-16 04:19

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_editprofileform_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofileform',
            name='bio',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
