# Generated by Django 3.2.8 on 2021-11-16 04:46

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_note_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
