# Generated by Django 3.2.8 on 2021-11-16 12:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_auto_20211116_0446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Question',
        ),
    ]
