# Generated by Django 3.2.8 on 2021-11-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_note_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='note_title',
        ),
    ]
