# Generated by Django 3.2.10 on 2021-12-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20211218_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='note_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
