# Generated by Django 3.2.10 on 2022-01-11 14:49

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20220110_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='note_custom',
            field=django_editorjs_fields.fields.EditorJsTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='note_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(null=True),
        ),
    ]
