# Generated by Django 3.2.10 on 2022-01-11 15:05

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20220111_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='note_custom',
        ),
        migrations.AlterField(
            model_name='question',
            name='note_editorjs',
            field=django_editorjs_fields.fields.EditorJsJSONField(null=True),
        ),
    ]
