# Generated by Django 3.2.10 on 2022-01-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
