# Generated by Django 3.2.10 on 2022-01-12 09:26

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=django_editorjs_fields.fields.EditorJsJSONField(null=True),
        ),
    ]
