# Generated by Django 3.2.10 on 2022-01-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='small_intro',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
