# Generated by Django 3.2.10 on 2022-01-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20220113_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='small_intro',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
