# Generated by Django 3.2.10 on 2022-01-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_question_total_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='total_question',
        ),
    ]
