# Generated by Django 3.2.10 on 2022-01-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaultprofile_photo.png', null=True, upload_to=''),
        ),
    ]
