# Generated by Django 3.2.10 on 2022-01-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20220117_0840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
