# Generated by Django 3.2.10 on 2022-01-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_delete_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updates',
            name='seen',
        ),
        migrations.AddField(
            model_name='updates',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
